[package]
name = "livekit-ffmpeg-repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-next = "6.0.0"
livekit = "0.1.3"
# livekit = { git = "https://github.com/livekit/client-sdk-rust" }