name: Build Release

on:
    workflow_dispatch:

jobs:
    build:
        name: Build ${{ matrix.build_name }}
        strategy:
            matrix:
                include:
                  - build_name: linux-x86_64
                    os: ubuntu-latest

                  - build_name: macos-x86_64
                    os: macos-latest
                    target: x86_64-apple-darwin
        
#                 ffmpeg does not cross-build to aarch64 in CI, so aarch64 releases must be manually added
#                  - build_name: macos-aarch64
#                    os: macos-latest
#                    target: aarch64-apple-darwin

                  - build_name: windows-x86_64
                    os: windows-latest
                    target: x86_64-pc-windows-msvc

        env:
            PACKAGE_FILE: ${{ 'repro' }}-${{ matrix.build_name }}.${{ startsWith(matrix.build_name, 'win') && 'zip' || 'tar.gz' }}
            CARGO_BUILD_DIR: target/${{ matrix.target }}/release

        runs-on: ${{ matrix.os }}
        steps:
          - name: Clone repo
            uses: actions/checkout@v3

          - uses: actions-rs/toolchain@v1
            with:
                profile: minimal
                toolchain: stable
                override: true

          - name: install ffmpeg deps (linux)
            if: runner.os == 'linux'
            run: sudo apt install -y --no-install-recommends clang curl pkg-config libavcodec-dev libavformat-dev libavutil-dev libavfilter-dev libavdevice-dev
          - name: install ffmpeg deps (macOs)
            if: runner.os == 'macos'
            run: brew install ffmpeg pkg-config          
          - name: install ffmpeg deps (windows)
            if: runner.os == 'windows'
            run: |
              $VCINSTALLDIR = $(& "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath)
              Add-Content $env:GITHUB_ENV "LIBCLANG_PATH=${VCINSTALLDIR}\VC\Tools\LLVM\x64\bin`n"
              Invoke-WebRequest "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z" -OutFile ffmpeg-release-full-shared.7z
              7z x ffmpeg-release-full-shared.7z
              mkdir ffmpeg
              mv ffmpeg-*/* ffmpeg/
              Add-Content $env:GITHUB_ENV "FFMPEG_DIR=${pwd}\ffmpeg`n"
              Add-Content $env:GITHUB_PATH "${pwd}\ffmpeg\bin`n"  

          - name: Cargo build
            run: cargo build --release ${{ matrix.target && '--target' }} ${{ matrix.target }}

          - name: Package common
            run: |
                mkdir package
                cp readme.md package/README.md
                cp LICENSE package/LICENSE
                cp -r assets package
            
          - name: Package Windows
            if: runner.os == 'Windows'
            continue-on-error: true
            run: |
                cp ${{ env.CARGO_BUILD_DIR }}/decentra-bevy.exe package/decentra-bevy.exe
                cp ${{ env.FFMPEG_DIR }}/bin/*.dll package
                7z a ${{ env.PACKAGE_FILE }} ./package/*

          - name: Package Other
            if: runner.os != 'Windows'
            continue-on-error: true
            run: |
                cp ${{ env.CARGO_BUILD_DIR }}/decentra-bevy package/decentra-bevy
                # We must enter the package/ directory in order to create a flat tarball (i.e. without a directory in it).
                cd package
                tar -czvf ../${{ env.PACKAGE_FILE }} *            

          - name: Upload package
            continue-on-error: true
            run: gh release upload "${{ needs.create-release.outputs.tag_name }}" "${{ env.PACKAGE_FILE }}"
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
